[project]
name = "ca-simulator"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.10"
dependencies = [
    "cryptography>=44.0.1",
    "flask>=3.1.0",
    "psycopg2>=2.9.10",
    "pycryptodome>=3.21.0",
    "requests>=2.32.3",
]
